// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJArGNfdXy0CclJwp15eXuMqnK-UJ6RJk',
    appId: '1:228337213146:android:66972f2032b4eadc3c8fe3',
    messagingSenderId: '228337213146',
    projectId: 'thechat-49e1c',
    databaseURL: 'https://thechat-49e1c.firebaseio.com',
    storageBucket: 'thechat-49e1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnMShiSd23LU81ZWQITN4Q66dRvLmXqT4',
    appId: '1:228337213146:ios:d33739164f61b2fc3c8fe3',
    messagingSenderId: '228337213146',
    projectId: 'thechat-49e1c',
    databaseURL: 'https://thechat-49e1c.firebaseio.com',
    storageBucket: 'thechat-49e1c.appspot.com',
    iosClientId: '228337213146-olp2q4qlpn36ee61p615ch24rj1kjioh.apps.googleusercontent.com',
    iosBundleId: 'org.inmanencia.thechat',
  );
}
